exclude:
  - 'src/epub/css/core.css'

linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  HexNotation:
    style: uppercase

  Indentation:
    enabled: true
    character: tab
    width: 1

  MergeableSelector:
    enabled: false

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: false

  SpaceAfterPropertyColon:
    style: at_least_one_space

  SpaceBeforeBrace:
    enabled: false

  VendorPrefix:
    enabled: false
